name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkoutt
        uses: actions/checkout@v1
      - name: Build and Test
        run: /usr/bin/xcodebuild test -project "$XC_PROJECT" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
    
